# Generated by Django 6.0.3 on 2026-03-24 10:16

from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


def migrate_shipping_addresses(apps, schema_editor):
    ShippingAddress = apps.get_model("shipping", "ShippingAddress")
    Address = apps.get_model("customers", "Address")

    if ShippingAddress.objects.count() == 0:
        return

    # Copy rows while preserving primary keys so existing Shipments keep working.
    for old in ShippingAddress.objects.all():
        Address.objects.update_or_create(
            id=old.id,
            defaults={
                "user_id": old.user_id,
                "full_name": old.full_name,
                "phone_number": old.phone,
                "address_line": old.address_line1,
                "city": old.city,
                "region": old.state,
                "country": old.country,
                "postal_code": old.postal_code,
                "is_default": old.is_default,
                "created_at": old.created_at,
                "updated_at": old.updated_at,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shippingaddress',
            name='shipping_sh_user_id_63a3e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='shippingaddress',
            name='shipping_sh_user_id_b55d72_idx',
        ),
        migrations.RunPython(migrate_shipping_addresses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='shipment',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='customers.address'),
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
