# Generated by Django 5.2 on 2026-03-10 11:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la marque', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version du nom', null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description de la marque')),
                ('logo', models.ImageField(blank=True, help_text='Logo de la marque', null=True, upload_to='brands/')),
                ('country', models.CharField(blank=True, help_text="Pays d'origine", max_length=50)),
                ('website', models.URLField(blank=True, help_text='Site web de la marque')),
                ('is_active', models.BooleanField(default=True, help_text='La marque est-elle active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='products_br_name_0925fd_idx'), models.Index(fields=['slug'], name='products_br_slug_d4d839_idx')],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du modèle', max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version du nom', null=True)),
                ('year_start', models.IntegerField(help_text='Année de début de production', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('year_end', models.IntegerField(blank=True, help_text='Année de fin de production', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('body_type', models.CharField(choices=[('sedan', 'Berline'), ('coupe', 'Coupé'), ('suv', 'SUV'), ('hatchback', 'Monospace'), ('station_wagon', 'Break'), ('van', 'Fourgonnette'), ('truck', 'Camion'), ('other', 'Autre')], default='sedan', help_text='Type de carrosserie', max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Image du modèle', null=True, upload_to='car_models/')),
                ('is_active', models.BooleanField(default=True, help_text='Le modèle est-il actif?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(help_text='Marque du véhicule', on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to='products.brand')),
            ],
            options={
                'verbose_name': 'Car Model',
                'verbose_name_plural': 'Car Models',
                'ordering': ['-year_start', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la catégorie', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version du nom', null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description de la catégorie')),
                ('image', models.ImageField(blank=True, help_text='Image de la catégorie', null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True, help_text='La catégorie est-elle active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='products_ca_name_693421_idx'), models.Index(fields=['slug'], name='products_ca_slug_da4386_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du produit', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version du nom', null=True, unique=True)),
                ('description', models.TextField(help_text='Description détaillée du produit')),
                ('sku', models.CharField(help_text='Stock Keeping Unit (référence du produit)', max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Prix unitaire de base', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Coût de revient', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_quantity', models.IntegerField(default=0, help_text='Quantité en stock', validators=[django.core.validators.MinValueValidator(0)])),
                ('low_stock_alert', models.IntegerField(default=10, help_text="Seuil d'alerte de stock bas", validators=[django.core.validators.MinValueValidator(0)])),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Poids en kg', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('dimensions', models.CharField(blank=True, help_text='Dimensions (L x l x H)', max_length=255)),
                ('warranty_months', models.IntegerField(default=12, help_text='Durée de garantie en mois', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Le produit est-il actif?')),
                ('is_featured', models.BooleanField(default=False, help_text='Produit en vedette?')),
                ('rating', models.FloatField(default=0.0, help_text='Note moyenne (0-5)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('number_of_reviews', models.IntegerField(default=0, help_text="Nombre d'avis clients", validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, help_text='Marque du produit (fabricant)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(blank=True, help_text='Catégorie du produit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
                ('compatible_car_models', models.ManyToManyField(blank=True, help_text='Modèles de voitures compatibles', related_name='products', to='products.carmodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image du produit', upload_to='products/')),
                ('alt_text', models.CharField(blank=True, help_text="Texte alternatif pour l'image", max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Image principale du produit?')),
                ('display_order', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Produit associé', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Product Images',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la variante (ex: Noir, Taille M)', max_length=100)),
                ('sku', models.CharField(help_text='SKU de la variante', max_length=100, unique=True)),
                ('attribute_name', models.CharField(choices=[('color', 'Couleur'), ('size', 'Taille'), ('version', 'Version'), ('material', 'Matière'), ('fit', 'Ajustement'), ('strength', 'Puissance'), ('other', 'Autre')], default='other', help_text="Type d'attribut", max_length=50)),
                ('attribute_value', models.CharField(help_text="Valeur de l'attribut", max_length=100)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, help_text='Modification de prix par rapport au produit principal', max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0, help_text='Quantité en stock pour cette variante', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='La variante est-elle disponible?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Produit parent', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Product Variants',
                'ordering': ['attribute_name', 'attribute_value'],
            },
        ),
        migrations.AddIndex(
            model_name='carmodel',
            index=models.Index(fields=['brand', 'name'], name='products_ca_brand_i_47e62e_idx'),
        ),
        migrations.AddIndex(
            model_name='carmodel',
            index=models.Index(fields=['slug'], name='products_ca_slug_9a911e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('brand', 'name', 'year_start')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='products_pr_brand_i_dc6890_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product'], name='products_pr_product_3d7874_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['is_primary'], name='products_pr_is_prim_b891de_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='products_pr_product_66459e_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku'], name='products_pr_sku_dcab68_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'attribute_value')},
        ),
    ]
