# Generated by Codex on 2026-03-24

from __future__ import annotations

from django.db import migrations


def _get_table_columns(schema_editor, table_name: str) -> set[str]:
    with schema_editor.connection.cursor() as cursor:
        return {c.name for c in schema_editor.connection.introspection.get_table_description(cursor, table_name)}


def ensure_stock_quantity_columns(apps, schema_editor):
    """
    Safety migration.

    Some environments have `products_product` / `products_productvariant` tables without the
    `stock_quantity` column even though migration `0001_initial` includes it (migration file
    was likely edited after being applied).

    This migration checks the live DB schema and adds the missing column(s) if needed.
    """

    Product = apps.get_model("products", "Product")
    ProductVariant = apps.get_model("products", "ProductVariant")

    product_cols = _get_table_columns(schema_editor, Product._meta.db_table)
    if "stock_quantity" not in product_cols:
        schema_editor.add_field(Product, Product._meta.get_field("stock_quantity"))

    variant_cols = _get_table_columns(schema_editor, ProductVariant._meta.db_table)
    if "stock_quantity" not in variant_cols:
        schema_editor.add_field(ProductVariant, ProductVariant._meta.get_field("stock_quantity"))


def revert_stock_quantity_columns(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    ProductVariant = apps.get_model("products", "ProductVariant")

    product_cols = _get_table_columns(schema_editor, Product._meta.db_table)
    if "stock_quantity" in product_cols:
        schema_editor.remove_field(Product, Product._meta.get_field("stock_quantity"))

    variant_cols = _get_table_columns(schema_editor, ProductVariant._meta.db_table)
    if "stock_quantity" in variant_cols:
        schema_editor.remove_field(ProductVariant, ProductVariant._meta.get_field("stock_quantity"))


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(ensure_stock_quantity_columns, revert_stock_quantity_columns),
    ]

