# Generated by Django 5.2 on 2026-03-16 13:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom de l'entrepôt", max_length=100, unique=True)),
                ('location', models.CharField(blank=True, help_text="Adresse ou localisation de l'entrepôt", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock_quantity',
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie'), ('ADJUSTMENT', 'Ajustement manuel')], help_text='Type de mouvement', max_length=20)),
                ('quantity', models.IntegerField(help_text='Quantité (positive pour IN, négative pour OUT)')),
                ('reference', models.CharField(blank=True, help_text="Référence externe (Order ID, cause d'ajustement...)", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='Quantité physique disponible', validators=[django.core.validators.MinValueValidator(0)])),
                ('reserved_quantity', models.IntegerField(default=0, help_text='Quantité réservée par des commandes non finalisées', validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, help_text='Produit principal', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='products.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Variante du produit (si applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='products.productvariant')),
                ('warehouse', models.ForeignKey(help_text='Entrepôt', on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='products.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
                'unique_together': {('warehouse', 'product', 'variant')},
            },
        ),
    ]
