# Generated by Django 5.2.12 on 2026-03-25 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_ensure_stock_quantity_columns'),
        ('products', '0002_warehouse_remove_product_stock_quantity_and_more'),
    ]

    operations = [
    ]
